version: "3.4"

services:
  kibana:
    build:
      context: ./build/kibana
    volumes:
      - ./build/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - mage