
version: "3.4"

services:
  php7-fpm:
    volumes:
      - ${PWD}/build/varnish/scripts/post-varnish.sh:/docker/scripts/post-varnish.sh
  varnish:
    build:
      context: ./build/varnish
    environment:
      - VCL_CONFIG=/varnish/data/varnish.vcl
      - VARNISHD_PARAMS=-p default_ttl=3600 -p default_grace=3600 -p max_retries=64
    ports:
      - 80:80
    depends_on:
      - php7-fpm
      - nginx
    networks:
      - mage
